server:
  port: 8081
spring:
  ## thymeleaf 模板配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/template
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: classpath:/static
## mybatis 配置
mybatis:
  type-aliases-package: com.recycle.model
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 用于雪花算法生成id
datacenterId: 2
workerId: 1

#开启sql日志
#第一种方式
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#第二种方式
#logging:
#  level:
#    com.recycle.mapper: debug
