server:
  port: 8081
spring:
  ## thymeleaf 模板配置
  thymeleaf:
    mode: HTML5
    encoding: UTF-8
    servlet:
      content-type: text/html
    cache: false
    prefix: classpath:/template
  mvc:
    static-path-pattern: /static/**
  ## 数据库驱动配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/recyle_admin_db?characterEncoding=utf8
    username: root
    password: zhouzhu
  web:
    resources:
      static-locations: classpath:/static
## mybatis 配置
mybatis:
  type-aliases-package: com.recycle.model
  mapper-locations: classpath:/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 用于雪花算法生成id
datacenterId: 2
workerId: 1
